name: ðŸš€ Deploy website on push

on:
  push:
    branches:
      - main  # of je gewenste branch

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“‚ Get latest code
        uses: actions/checkout@v3

      - name: ðŸ“¤ Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.fit-track.nl
          username: ${{ secrets.FTPUSERNAME }}
          password: ${{ secrets.FTPPASSWORD }}
          protocol: ftps
          server-dir: public_html/travel-booking-website/ # waar op de server wil je het neerzetten?
